/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';

/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'apartmentNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'ruralRoute'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'municipality'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'stateProvince'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'mediaOutletId'?: string;
    /**
     * 
     * @type {MediaOutlet}
     * @memberof Address
     */
    'mediaOutlet'?: MediaOutlet;
}

