/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaContactPhoneDto } from './media-contact-phone-dto';

/**
 * 
 * @export
 * @interface ContactOutletDto
 */
export interface ContactOutletDto {
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'outletName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'outletId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'outletEmail'?: string | null;
    /**
     * 
     * @type {Array<MediaContactPhoneDto>}
     * @memberof ContactOutletDto
     */
    'contactPhones'?: Array<MediaContactPhoneDto> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ContactOutletDto
     */
    'isMajorMedia'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'jobTitle'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'contactEmail'?: string | null;
}

