/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactOutletDto } from './contact-outlet-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaRequestDto } from './media-request-dto';

/**
 * 
 * @export
 * @interface ContactDto
 */
export interface ContactDto {
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ContactDto
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContactDto
     */
    'jobTitle'?: string | null;
    /**
     * 
     * @type {Array<ContactOutletDto>}
     * @memberof ContactDto
     */
    'outlets'?: Array<ContactOutletDto> | null;
    /**
     * 
     * @type {Array<MediaRequestDto>}
     * @memberof ContactDto
     */
    'requests'?: Array<MediaRequestDto> | null;
}

