/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactOutletDto
 */
export interface ContactOutletDto {
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'outletName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContactOutletDto
     */
    'outletEmail'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContactOutletDto
     */
    'contactEmails'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContactOutletDto
     */
    'contactPhones'?: Array<string> | null;
}

