/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressDto } from './address-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PhoneNumberDto } from './phone-number-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SocialMediaLinkDto } from './social-media-link-dto';

/**
 * 
 * @export
 * @interface CreateOrganizationDto
 */
export interface CreateOrganizationDto {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    'outletName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    'organizationType': string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateOrganizationDto
     */
    'isMajorMedia'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    'parentOutletId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationDto
     */
    'website'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOrganizationDto
     */
    'mediaTypeIds'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOrganizationDto
     */
    'writtenLanguageIds'?: Array<number> | null;
    /**
     * 
     * @type {Array<PhoneNumberDto>}
     * @memberof CreateOrganizationDto
     */
    'phoneNumbers'?: Array<PhoneNumberDto> | null;
    /**
     * 
     * @type {Array<SocialMediaLinkDto>}
     * @memberof CreateOrganizationDto
     */
    'socialMediaLinks'?: Array<SocialMediaLinkDto> | null;
    /**
     * 
     * @type {AddressDto}
     * @memberof CreateOrganizationDto
     */
    'address'?: AddressDto;
}

