/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Ministry } from './ministry';

/**
 * 
 * @export
 * @interface MediaRequestDto
 */
export interface MediaRequestDto {
    /**
     * 
     * @type {string}
     * @memberof MediaRequestDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRequestDto
     */
    'requestTitle'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaRequestDto
     */
    'receivedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRequestDto
     */
    'deadline'?: string;
    /**
     * 
     * @type {Ministry}
     * @memberof MediaRequestDto
     */
    'leadMinistry'?: Ministry;
    /**
     * 
     * @type {number}
     * @memberof MediaRequestDto
     */
    'requestNo'?: number;
}

