/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaContact } from './media-contact';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';
// May contain unused imports in some cases
// @ts-ignore
import type { Ministry } from './ministry';
// May contain unused imports in some cases
// @ts-ignore
import type { RequestResolution } from './request-resolution';
// May contain unused imports in some cases
// @ts-ignore
import type { RequestStatus } from './request-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RequestType } from './request-type';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface MediaRequest
 */
export interface MediaRequest {
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof MediaRequest
     */
    'requestStatusId': number;
    /**
     * 
     * @type {RequestStatus}
     * @memberof MediaRequest
     */
    'requestStatus'?: RequestStatus;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'requestTitle': string;
    /**
     * 
     * @type {number}
     * @memberof MediaRequest
     */
    'requestTypeId': number;
    /**
     * 
     * @type {RequestType}
     * @memberof MediaRequest
     */
    'requestType'?: RequestType;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'requestDetails': string;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'requestorContactId': string;
    /**
     * 
     * @type {MediaContact}
     * @memberof MediaRequest
     */
    'requestorContact'?: MediaContact;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'requestorOutletId'?: string | null;
    /**
     * 
     * @type {MediaOutlet}
     * @memberof MediaRequest
     */
    'requestorOutlet'?: MediaOutlet;
    /**
     * 
     * @type {number}
     * @memberof MediaRequest
     */
    'requestResolutionId'?: number | null;
    /**
     * 
     * @type {RequestResolution}
     * @memberof MediaRequest
     */
    'requestResolution'?: RequestResolution;
    /**
     * 
     * @type {number}
     * @memberof MediaRequest
     */
    'leadMinistryId'?: number | null;
    /**
     * 
     * @type {Ministry}
     * @memberof MediaRequest
     */
    'leadMinistry'?: Ministry;
    /**
     * 
     * @type {Array<Ministry>}
     * @memberof MediaRequest
     */
    'additionalMinistries'?: Array<Ministry> | null;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'assignedUserId'?: string | null;
    /**
     * 
     * @type {User}
     * @memberof MediaRequest
     */
    'assignedUser'?: User;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'fyiContactUserId'?: string | null;
    /**
     * 
     * @type {User}
     * @memberof MediaRequest
     */
    'fyiContactUser'?: User;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'response'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MediaRequest
     */
    'requestNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'receivedOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaRequest
     */
    'deadline'?: string;
}

