/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutletContactRelationship } from './media-outlet-contact-relationship';

/**
 * 
 * @export
 * @interface MediaContactEmail
 */
export interface MediaContactEmail {
    /**
     * 
     * @type {string}
     * @memberof MediaContactEmail
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaContactEmail
     */
    'outletContactRelationshipId'?: string;
    /**
     * 
     * @type {MediaOutletContactRelationship}
     * @memberof MediaContactEmail
     */
    'outletContactRelationship'?: MediaOutletContactRelationship;
    /**
     * 
     * @type {string}
     * @memberof MediaContactEmail
     */
    'emailAddress'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MediaContactEmail
     */
    'isPrimary'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MediaContactEmail
     */
    'isActive'?: boolean;
}

