/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MediaContactSimpleDto
 */
export interface MediaContactSimpleDto {
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'jobTitle'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaContactSimpleDto
     */
    'fullName'?: string | null;
}

