/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaContact } from './media-contact';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaContactEmail } from './media-contact-email';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaContactPhone } from './media-contact-phone';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';

/**
 * 
 * @export
 * @interface MediaOutletContactRelationship
 */
export interface MediaOutletContactRelationship {
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'mediaOutletId'?: string;
    /**
     * 
     * @type {MediaOutlet}
     * @memberof MediaOutletContactRelationship
     */
    'mediaOutlet'?: MediaOutlet;
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'mediaContactId'?: string;
    /**
     * 
     * @type {MediaContact}
     * @memberof MediaOutletContactRelationship
     */
    'mediaContact'?: MediaContact;
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'startDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaOutletContactRelationship
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {Array<MediaContactEmail>}
     * @memberof MediaOutletContactRelationship
     */
    'emails'?: Array<MediaContactEmail> | null;
    /**
     * 
     * @type {Array<MediaContactPhone>}
     * @memberof MediaOutletContactRelationship
     */
    'phoneNumbers'?: Array<MediaContactPhone> | null;
}

