/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaRequest } from './media-request';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaType } from './media-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PhoneNumber } from './phone-number';
// May contain unused imports in some cases
// @ts-ignore
import type { SocialMedia } from './social-media';
// May contain unused imports in some cases
// @ts-ignore
import type { WrittenLanguage } from './written-language';

/**
 * 
 * @export
 * @interface MediaOutlet
 */
export interface MediaOutlet {
    /**
     * 
     * @type {string}
     * @memberof MediaOutlet
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaOutlet
     */
    'outletName': string;
    /**
     * 
     * @type {boolean}
     * @memberof MediaOutlet
     */
    'isMajorMedia'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MediaOutlet
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof MediaOutlet
     */
    'website'?: string | null;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof MediaOutlet
     */
    'phoneNumber'?: PhoneNumber;
    /**
     * 
     * @type {Array<Address>}
     * @memberof MediaOutlet
     */
    'addresses'?: Array<Address> | null;
    /**
     * 
     * @type {Array<MediaType>}
     * @memberof MediaOutlet
     */
    'mediaTypes'?: Array<MediaType> | null;
    /**
     * 
     * @type {Array<WrittenLanguage>}
     * @memberof MediaOutlet
     */
    'writtenLanguages'?: Array<WrittenLanguage> | null;
    /**
     * 
     * @type {Array<SocialMedia>}
     * @memberof MediaOutlet
     */
    'socialMedias'?: Array<SocialMedia> | null;
    /**
     * 
     * @type {Array<MediaRequest>}
     * @memberof MediaOutlet
     */
    'mediaRequests'?: Array<MediaRequest> | null;
}

