/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaContactPhoneType } from './media-contact-phone-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutletContactRelationship } from './media-outlet-contact-relationship';

/**
 * 
 * @export
 * @interface MediaContactPhone
 */
export interface MediaContactPhone {
    /**
     * 
     * @type {string}
     * @memberof MediaContactPhone
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MediaContactPhone
     */
    'outletContactRelationshipId'?: string;
    /**
     * 
     * @type {MediaOutletContactRelationship}
     * @memberof MediaContactPhone
     */
    'outletContactRelationship'?: MediaOutletContactRelationship;
    /**
     * 
     * @type {string}
     * @memberof MediaContactPhone
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MediaContactPhone
     */
    'extension'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MediaContactPhone
     */
    'phoneTypeId'?: number;
    /**
     * 
     * @type {MediaContactPhoneType}
     * @memberof MediaContactPhone
     */
    'phoneType'?: MediaContactPhoneType;
    /**
     * 
     * @type {boolean}
     * @memberof MediaContactPhone
     */
    'isActive'?: boolean;
}

