/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';

/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
    /**
     * 
     * @type {number}
     * @memberof MediaType
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof MediaType
     */
    'name'?: string | null;
    /**
     * 
     * @type {Array<MediaOutlet>}
     * @memberof MediaType
     */
    'mediaOutlets'?: Array<MediaOutlet> | null;
}

