/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrganizationListDto
 */
export interface OrganizationListDto {
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationListDto
     */
    'isMajorMedia'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrganizationListDto
     */
    'mediaTypes'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationListDto
     */
    'parentId'?: string | null;
}

