/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PhoneNumber } from './phone-number';

/**
 * 
 * @export
 * @interface PersonalPhoneNumber
 */
export interface PersonalPhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof PersonalPhoneNumber
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalPhoneNumber
     */
    'contactId': string;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof PersonalPhoneNumber
     */
    'phoneNumber': PhoneNumber;
}

