/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';

/**
 * 
 * @export
 * @interface PhoneNumber
 */
export interface PhoneNumber {
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    'phoneType': string;
    /**
     * 
     * @type {string}
     * @memberof PhoneNumber
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PhoneNumber
     */
    'phoneLineNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof PhoneNumber
     */
    'phoneExtension'?: number | null;
    /**
     * 
     * @type {Array<MediaOutlet>}
     * @memberof PhoneNumber
     */
    'mediaOutlets'?: Array<MediaOutlet> | null;
}

