/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SocialMediaDto
 */
export interface SocialMediaDto {
    /**
     * 
     * @type {number}
     * @memberof SocialMediaDto
     */
    'companyId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SocialMediaDto
     */
    'url'?: string | null;
}

