/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaContact } from './media-contact';
// May contain unused imports in some cases
// @ts-ignore
import type { MediaOutlet } from './media-outlet';

/**
 * 
 * @export
 * @interface SocialMedia
 */
export interface SocialMedia {
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    'company'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    'socialProfileUrl'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SocialMedia
     */
    'socialMediaCompanyId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    'mediaOutletId'?: string | null;
    /**
     * 
     * @type {MediaOutlet}
     * @memberof SocialMedia
     */
    'mediaOutlet'?: MediaOutlet;
    /**
     * 
     * @type {string}
     * @memberof SocialMedia
     */
    'mediaContactId'?: string | null;
    /**
     * 
     * @type {MediaContact}
     * @memberof SocialMedia
     */
    'mediaContact'?: MediaContact;
}

