/* tslint:disable */
/* eslint-disable */
/**
 * GCPE Media Hub 2.0 API
 * GCPE Media Hub 2.0
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api//media-contacts-api';
export * from './api//media-outlets-api';
export * from './api//media-requests-api';
export * from './api//media-types-api';
export * from './api//ministries-api';
export * from './api//request-resolutions-api';
export * from './api//request-statuses-api';
export * from './api//request-types-api';
export * from './api//secure-api';
export * from './api//users-api';

